### ISSUE TITLE
Possible problem with xcoreCatalogProductAttributeSetGroupInfo

### ISSUE THREAD

**Issue by NickMulderLinq5** [dealer4dealer/magento1-soapapi#17]
![afbeelding](https://cloud.githubusercontent.com/assets/26714902/24358438/666c6a66-1301-11e7-8725-cab49b18b971.png)

top without WS-I -array with 5 values
bottom with WS-I - empty object

**Comment by NickMulderLinq5** [comment]
![afbeelding](https://cloud.githubusercontent.com/assets/26714902/24359023/546f18d4-1303-11e7-94f2-73f3a87539d8.png)

vanuit dezelfde store als met WS-I aan.

**Comment by HenriNijborg** [comment]
Problem solved in version 1.4.3
