### ISSUE TITLE
Large quantities of entities

### ISSUE THREAD

**Issue by sandermangel** [dealer4dealer/magento1-soapapi#5]
The API is great for transmitting data but getting detailed info requires a call per entity (order, customer, product). 
Querying the API often can lead to high loads on the server and syncing data the first time would possibly paralyse the whole system if live.

Is there a way to prevent this, have you thought about a way to keep the load down, chunck batches, etc.

**Comment by michielfb** [comment]
Currently there is no way to prevent this. After the activation we call catalogProductList to fetch a list of all products. For each product in the list we will call catalogProductInfo. 

In future releases of the xCore we plan to support web hooks to prevent this issue..

**Comment by HenriNijborg** [comment]
We've added xcoreCatalogProductList function to support limitation of the product list.
